### PR TITLE
Add append css and js file and init

### PR DESCRIPTION
**Pull request by ValhallaSkies**

### CODE REVIEW

**Comment by pacificnm** [comment]
@ValhallaSkies which of these do we keep?

<<<<<<< develop
	->appendFile("/assets/js/ubislider.min.js")
=======
	->appendFile("/assets/js/jquery.elevatezoom.js")
>>>>>>> master

**Comment by pacificnm** [comment]
<<<<<<< develop
	->appendFile("/assets/js/ubislider.min.js")
=======
	->appendFile("/assets/js/jquery.elevatezoom.js")
>>>>>>> master

**Comment by ValhallaSkies** [comment]
Im going to use the elevate as well as an option.

**Comment by ValhallaSkies** [comment]
@pacificnm So keep both 

appendFile("/assets/js/ubislider.min.js")

appendFile("/assets/js/jquery.elevatezoom.js")

**Pull request merged**
